# open-ube-root-chamber — simulation/generate_config_h.py
#
# Reads config.py and writes firmware-esp32/config.h
# This is the bridge between Python and C++.
#
# Run manually:   python simulation/generate_config_h.py
# Run in CI:      called automatically by simulate.yml before the simulation
#
# After running this, flash main.ino as normal.
# main.ino will pick up the new values via #include "config.h"

import os
import sys

# Allow running from repo root or from simulation/ folder
sys.path.insert(0, os.path.dirname(__file__))
import config

# Output path — relative to repo root
OUTPUT_PATH = os.path.join(
    os.path.dirname(__file__),  # simulation/
    "..",                        # repo root
    "firmware-esp32",
    "config.h"
)

TEMPLATE = """// open-ube-root-chamber — firmware-esp32/config.h
//
// AUTO-GENERATED by simulation/generate_config_h.py
// DO NOT EDIT MANUALLY — edit simulation/config.py instead, then re-run:
//   python simulation/generate_config_h.py
//
// Generated from: simulation/config.py
// Values in sync with: simulation/simulate.py, edge-vision/root_vigor.py

#ifndef CONFIG_H
#define CONFIG_H

// ── Controller setpoints (used by pid_controller.h) ─────────────────────────
const float HUMIDITY_TARGET    = {HUMIDITY_TARGET}f;
const float TEMPERATURE_TARGET = {TEMPERATURE_TARGET}f;
const float DEADBAND           = {DEADBAND}f;

// ── Safe operating bands ────────────────────────────────────────────────────
const float HUMIDITY_SAFE_LOW  = {HUMIDITY_SAFE_LOW}f;
const float HUMIDITY_SAFE_HIGH = {HUMIDITY_SAFE_HIGH}f;
const float TEMP_SAFE_LOW      = {TEMP_SAFE_LOW}f;
const float TEMP_SAFE_HIGH     = {TEMP_SAFE_HIGH}f;

// ── Root vigor thresholds (mirrors edge-vision/root_vigor.py) ───────────────
const float HIGH_VIGOR_CM = {HIGH_VIGOR_CM}f;
const float GROWING_CM    = {GROWING_CM}f;

// ── Firmware timing ─────────────────────────────────────────────────────────
const unsigned long SENSOR_INTERVAL_MS = 2000;  // DHT22 read every 2s
const unsigned long SERIAL_LOG_MS      = 5000;  // Serial.println every 5s

#endif // CONFIG_H
""".format(
    HUMIDITY_TARGET    = config.HUMIDITY_TARGET,
    TEMPERATURE_TARGET = config.TEMPERATURE_TARGET,
    DEADBAND           = config.DEADBAND,
    HUMIDITY_SAFE_LOW  = config.HUMIDITY_SAFE_LOW,
    HUMIDITY_SAFE_HIGH = config.HUMIDITY_SAFE_HIGH,
    TEMP_SAFE_LOW      = config.TEMP_SAFE_LOW,
    TEMP_SAFE_HIGH     = config.TEMP_SAFE_HIGH,
    HIGH_VIGOR_CM      = config.HIGH_VIGOR_CM,
    GROWING_CM         = config.GROWING_CM,
)

def main():
    out = os.path.normpath(OUTPUT_PATH)
    os.makedirs(os.path.dirname(out), exist_ok=True)

    with open(out, "w") as f:
        f.write(TEMPLATE)

    print("[generate_config_h] Written to: {}".format(out))
    print("  HUMIDITY_TARGET    = {}".format(config.HUMIDITY_TARGET))
    print("  TEMPERATURE_TARGET = {}".format(config.TEMPERATURE_TARGET))
    print("  DEADBAND           = {}".format(config.DEADBAND))
    print("  HIGH_VIGOR_CM      = {}".format(config.HIGH_VIGOR_CM))
    print("  GROWING_CM         = {}".format(config.GROWING_CM))
    print("\nNext step: flash firmware-esp32/main.ino to your ESP32.")

if __name__ == "__main__":
    main()